Use OpenShift S2I CentOS image, and create data/ directories

diff --git a/openshift-pgsql10-master-centos7/s2i/bin/run b/openshift-pgsql10-master-centos7/s2i/bin/run
--- a/openshift-pgsql10-master-centos7/s2i/bin/run
+++ b/openshift-pgsql10-master-centos7/s2i/bin/run
@@ -21,7 +21,51 @@
 # SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 #
 
-if [ ! -f /pgdata/PG_VERSION ]; then
+REGEX_IDENTIFIER='^[a-zA-Z_][a-zA-Z0-9_]*$'
+REGEX_PASSWORD='^[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]+$'
+REGEX_NUMBER='^[1-9][0-9]*$'
+
+function usage() {
+  if [ $# == 1 ]; then
+    echo >&2 "error: $1"
+  fi
+
+  cat >&2 <<EOF
+Required environment variables:
+  PG_DATABASE ($PG_DATABASE) (regex: '$REGEX_IDENTIFIER')
+  PG_USER_NAME ($PG_USER_NAME) (regex: '$REGEX_IDENTIFIER')
+  PG_USER_PASSWORD ($PG_USER_PASSWORD) (regex: '$REGEX_PASSWORD')
+  PG_REPLICATION_NAME ($PG_REPLICATION_NAME) (regex: '$REGEX_IDENTIFIER')
+  PG_REPLICATION_PASSWORD ($PG_REPLICATION_PASSWORD) (regex: '$REGEX_PASSWORD')
+  PG_NETWORK_MASK ($PG_NETWORK_MASK)
+
+Optional environment variables:
+  PG_MAX_CONNECTIONS ($PG_MAX_CONNECTIONS) (default: 100) (regex: '$REGEX_NUMBER')
+  PG_SHARED_BUFFERS ($PG_SHARED_BUFFERS) (default: 256 MB) (regex: '$REGEX_NUMBER')
+  PG_WORK_MEM ($PG_WORK_MEM) (default: 8 MB) (regex: '$REGEX_NUMBER')
+  PG_MAX_PARALLEL_WORKERS ($PG_MAX_PARALLEL_WORKERS) (default: 8) (regex: '$REGEX_NUMBER')
+  PG_EFFECTIVE_CACHE_SIZE ($PG_EFFECTIVE_CACHE_SIZE) (default: 1 GB) (regex: '$REGEX_NUMBER')
+  PG_MAX_WAL_SIZE ($PG_MAX_WAL_SIZE) (default: 1 GB) (regex: '$REGEX_NUMBER')
+
+For more information visit https://github.com/jesperpedersen/openshift-pgsql
+EOF
+  exit 1
+}
+
+# Generate passwd file based on current uid
+function generate_passwd_file() {
+  export USER_ID=$(id -u)
+  export GROUP_ID=$(id -g)
+  grep -v ^postgres /etc/passwd > "$HOME/passwd"
+  echo "postgres:x:${USER_ID}:${GROUP_ID}:PostgreSQL Server:/pgdata:/bin/bash" >> "$HOME/passwd"
+  export LD_PRELOAD='/usr/lib64/libnss_wrapper.so'
+  export NSS_WRAPPER_PASSWD=$HOME/passwd
+  export NSS_WRAPPER_GROUP=/etc/group
+}
+
+generate_passwd_file
+
+if [ ! -f /pgdata/data/PG_VERSION ]; then
     export PG_MAX_CONNECTIONS=${PG_MAX_CONNECTIONS:-100}
     export PG_SHARED_BUFFERS=${PG_SHARED_BUFFERS:-256}
     export PG_WORK_MEM=${PG_WORK_MEM:-8}
@@ -45,7 +89,29 @@ if [ ! -f /pgdata/PG_VERSION ]; then
         exit 1
     fi
     
-    /usr/pgsql-10/bin/initdb -k -X /pgwal/ /pgdata/
+    [[ "${PG_DATABASE}" =~ $REGEX_IDENTIFIER ]] || usage
+    [[ "${PG_USER_NAME}" =~ $REGEX_IDENTIFIER ]] || usage
+    [[ "${PG_USER_PASSWORD}" =~ $REGEX_PASSWORD ]] || usage
+    [[ "${PG_REPLICATION_NAME}" =~ $REGEX_IDENTIFIER ]] || usage
+    [[ "${PG_REPLICATION_PASSWORD}" =~ $REGEX_PASSWORD ]] || usage
+
+    [[ "${PG_MAX_CONNECTIONS}" =~ $REGEX_NUMBER ]] || usage
+    [[ "${PG_SHARED_BUFFERS}" =~ $REGEX_NUMBER ]] || usage
+    [[ "${PG_WORK_MEM}" =~ $REGEX_NUMBER ]] || usage
+    [[ "${PG_MAX_PARALLEL_WORKERS}" =~ $REGEX_NUMBER ]] || usage
+    [[ "${PG_EFFECTIVE_CACHE_SIZE}" =~ $REGEX_NUMBER ]] || usage
+    [[ "${PG_MAX_WAL_SIZE}" =~ $REGEX_NUMBER ]] || usage
+
+    [ ${#PG_DATABASE} -le 63 ] || usage "Database name too long (maximum 63 characters)"
+    [ ${#PG_USER_NAME} -le 63 ] || usage "PostgreSQL username too long (maximum 63 characters)"
+    [ ${#PG_REPLICATION_NAME} -le 63 ] || usage "PostgreSQL replication name too long (maximum 63 characters)"
+
+    mkdir /pgdata/data
+    mkdir /pgwal/data
+    chmod 700 /pgdata/data
+    chmod 700 /pgwal/data
+
+    /usr/pgsql-10/bin/initdb -k -X /pgwal/data /pgdata/data
 
     sed -i "s/PG_MAX_CONNECTIONS/$PG_MAX_CONNECTIONS/g" /conf/postgresql.conf
     sed -i "s/PG_SHARED_BUFFERS/$PG_SHARED_BUFFERS/g" /conf/postgresql.conf
@@ -59,28 +125,30 @@ if [ ! -f /pgdata/PG_VERSION ]; then
     sed -i "s/PG_REPLICATION_NAME/$PG_REPLICATION_NAME/g" /conf/pg_hba.conf
     sed -i "s/PG_NETWORK_MASK/$PG_NETWORK_MASK/g" /conf/pg_hba.conf
 
-    if [ -f /pgconf/root.crt ] && [ -f /pgconf/server.crt ] && [ -f /pgconf/server.key ]; then
+    if [ -f /pgconf/data/root.crt ] && [ -f /pgconf/data/server.crt ] && [ -f /pgconf/data/server.key ]; then
         sed -i "s/ssl = off/ssl = on/g" /conf/postgresql.conf
         sed -i "s/SSL/ssl/g" /conf/pg_hba.conf
         sed -i "s/CERT/clientcert=1/g" /conf/pg_hba.conf
 
-        cp /pgconf/root.crt /pgdata
-        cp /pgconf/server.crt /pgdata
-        cp /pgconf/server.key /pgdata
+        cp /pgconf/data/root.crt /pgdata/data
+        cp /pgconf/data/server.crt /pgdata/data
+        cp /pgconf/data/server.key /pgdata/data
     else
         sed -i "s/SSL//g" /conf/pg_hba.conf
         sed -i "s/CERT//g" /conf/pg_hba.conf
     fi
 
-    cp /conf/postgresql.conf /pgdata/
-    cp /conf/pg_hba.conf /pgdata/
+    cp /conf/postgresql.conf /pgdata/data
+    cp /conf/pg_hba.conf /pgdata/data
 
-    if [ -f /pgdata/server.key ]; then
-        chmod 0600 /pgdata/server.key
+    if [ -f /pgdata/data/server.key ]; then
+        chmod 0600 /pgdata/data/server.key
     fi
 
-    (crontab -l ; echo "00 06  *   *   0     /usr/bin/pgbackrest --type=full --stanza=main backup") | crontab -
-    (crontab -l ; echo "00 06  *   *   1-6   /usr/bin/pgbackrest --type=diff --stanza=main backup") | crontab -
+    mkdir /pgbackup/data
+
+    # (crontab -l ; echo "00 06  *   *   0     /usr/bin/pgbackrest --type=full --stanza=main backup") | crontab -
+    # (crontab -l ; echo "00 06  *   *   1-6   /usr/bin/pgbackrest --type=diff --stanza=main backup") | crontab -
     
     sed -i "s/PG_DATABASE_ENCODING/$PG_DATABASE_ENCODING/g" /conf/setup.sql
     sed -i "s/PG_DATABASE/$PG_DATABASE/g" /conf/setup.sql
@@ -89,10 +157,10 @@ if [ ! -f /pgdata/PG_VERSION ]; then
     sed -i "s/PG_REPLICATION_NAME/$PG_REPLICATION_NAME/g" /conf/setup.sql
     sed -i "s/PG_REPLICATION_PASSWORD/$PG_REPLICATION_PASSWORD/g" /conf/setup.sql
 
-    /usr/pgsql-10/bin/pg_ctl -D /pgdata/ start
+    /usr/pgsql-10/bin/pg_ctl -D /pgdata/data start
     /usr/pgsql-10/bin/psql -q -f /conf/setup.sql postgres
     /usr/bin/pgbackrest --stanza=main stanza-create
-    /usr/pgsql-10/bin/pg_ctl -D /pgdata/ stop
+    /usr/pgsql-10/bin/pg_ctl -D /pgdata/data stop
 fi
 
-exec /usr/pgsql-10/bin/postgres -D /pgdata/ "$@"
+exec /usr/pgsql-10/bin/postgres -D /pgdata/data "$@"
diff --git a/openshift-pgsql10-slave-centos7/s2i/bin/run b/openshift-pgsql10-slave-centos7/s2i/bin/run
--- a/openshift-pgsql10-slave-centos7/s2i/bin/run
+++ b/openshift-pgsql10-slave-centos7/s2i/bin/run
@@ -21,7 +21,40 @@
 # SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 #
 
-if [ ! -f /pgdata/PG_VERSION ]; then
+REGEX_IDENTIFIER='^[a-zA-Z_][a-zA-Z0-9_]*$'
+REGEX_PASSWORD='^[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]+$'
+REGEX_NUMBER='^[1-9][0-9]*$'
+
+function usage() {
+  if [ $# == 1 ]; then
+    echo >&2 "error: $1"
+  fi
+
+  cat >&2 <<EOF
+Required environment variables:
+  PG_MASTER ($PG_MASTER)
+  PG_REPLICATION_NAME ($PG_REPLICATION_NAME) (regex: '$REGEX_IDENTIFIER')
+  PG_REPLICATION_PASSWORD ($PG_REPLICATION_PASSWORD) (regex: '$REGEX_PASSWORD')
+
+For more information visit https://github.com/jesperpedersen/openshift-pgsql
+EOF
+  exit 1
+}
+
+# Generate passwd file based on current uid
+function generate_passwd_file() {
+  export USER_ID=$(id -u)
+  export GROUP_ID=$(id -g)
+  grep -v ^postgres /etc/passwd > "$HOME/passwd"
+  echo "postgres:x:${USER_ID}:${GROUP_ID}:PostgreSQL Server:/pgdata:/bin/bash" >> "$HOME/passwd"
+  export LD_PRELOAD='/usr/lib64/libnss_wrapper.so'
+  export NSS_WRAPPER_PASSWD=$HOME/passwd
+  export NSS_WRAPPER_GROUP=/etc/group
+}
+
+generate_passwd_file
+
+if [ ! -f /pgdata/data/PG_VERSION ]; then
     export PG_MASTER=${PG_MASTER}
     export PG_REPLICATION_NAME=${PG_REPLICATION_NAME}
     export PG_REPLICATION_PASSWORD=${PG_REPLICATION_PASSWORD}
@@ -32,11 +65,16 @@ if [ ! -f /pgdata/PG_VERSION ]; then
         exit 1
     fi
 
-    if [ -f /pgconf/root.crt ] && [ -f /pgconf/postgresql.crt ] && [ -f /pgconf/postgresql.key ]; then
+    [[ "${PG_REPLICATION_NAME}" =~ $REGEX_IDENTIFIER ]] || usage
+    [[ "${PG_REPLICATION_PASSWORD}" =~ $REGEX_PASSWORD ]] || usage
+
+    [ ${#PG_REPLICATION_NAME} -le 63 ] || usage "PostgreSQL replication name too long (maximum 63 characters)"
+
+    if [ -f /pgconf/data/root.crt ] && [ -f /pgconf/data/postgresql.crt ] && [ -f /pgconf/data/postgresql.key ]; then
         mkdir ~/.postgresql
-        cp /pgconf/root.crt ~/.postgresql
-        cp /pgconf/postgresql.crt ~/.postgresql
-        cp /pgconf/postgresql.key ~/.postgresql
+        cp /pgconf/data/root.crt ~/.postgresql
+        cp /pgconf/data/postgresql.crt ~/.postgresql
+        cp /pgconf/data/postgresql.key ~/.postgresql
         chmod 0600 ~/.postgresql/postgresql.key
 
         sed -i "s/SSL/ sslmode=verify-ca/g" /conf/recovery.conf
@@ -44,20 +82,24 @@ if [ ! -f /pgdata/PG_VERSION ]; then
         sed -i "s/SSL//g" /conf/recovery.conf
     fi
 
-    PGPASSWORD="$PG_REPLICATION_PASSWORD" /usr/pgsql-10/bin/pg_basebackup -X stream --no-password -c fast -h ${PG_MASTER} -U ${PG_REPLICATION_NAME} -D /pgdata
+    mkdir /pgdata/data/
+
+    PGPASSWORD="$PG_REPLICATION_PASSWORD" /usr/pgsql-10/bin/pg_basebackup -X stream --no-password -c fast -h ${PG_MASTER} -U ${PG_REPLICATION_NAME} -D /pgdata/data/
 
     sed -i "s/PG_MASTER/$PG_MASTER/g" /conf/recovery.conf
     sed -i "s/PG_REPLICATION_NAME/$PG_REPLICATION_NAME/g" /conf/recovery.conf
     sed -i "s/PG_REPLICATION_PASSWORD/$PG_REPLICATION_PASSWORD/g" /conf/recovery.conf
 
-    cp /conf/recovery.conf /pgdata/
+    cp /conf/recovery.conf /pgdata/data/
 
-    (crontab -l ; echo "00 06  *   *   0     /usr/bin/pgbackrest --type=full --stanza=main backup") | crontab -
-    (crontab -l ; echo "00 06  *   *   1-6   /usr/bin/pgbackrest --type=diff --stanza=main backup") | crontab -
+    mkdir /pgbackup/data/
 
-    /usr/pgsql-10/bin/pg_ctl -D /pgdata/ start
+    # (crontab -l ; echo "00 06  *   *   0     /usr/bin/pgbackrest --type=full --stanza=main backup") | crontab -
+    # (crontab -l ; echo "00 06  *   *   1-6   /usr/bin/pgbackrest --type=diff --stanza=main backup") | crontab -
+
+    /usr/pgsql-10/bin/pg_ctl -D /pgdata/data/ start
     /usr/bin/pgbackrest --stanza=main stanza-create
-    /usr/pgsql-10/bin/pg_ctl -D /pgdata/ stop
+    /usr/pgsql-10/bin/pg_ctl -D /pgdata/data/ stop
 fi
 
-exec /usr/pgsql-10/bin/postgres -D /pgdata/ "$@"
+exec /usr/pgsql-10/bin/postgres -D /pgdata/data/ "$@"
